id: ADD7DD3FF
base_file: fDC51.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.040726
  last_modified_at: 2022-06-19 17:46:50.040729
