id: ADD7DD3FF
base_file: fA5DA.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.986963
  last_modified_at: 2022-06-19 17:46:49.986966
