id: ADD7DD3FF
base_file: fE7A3.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.051143
  last_modified_at: 2022-06-19 17:46:50.051146
