id: ADD7DD3FF
base_file: fB3B9.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.008490
  last_modified_at: 2022-06-19 17:46:50.008493
