id: ADD7DD3FF
base_file: f35B8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.918203
  last_modified_at: 2022-06-19 17:46:49.918207
