id: ADD7DD3FF
base_file: fD373.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.031584
  last_modified_at: 2022-06-19 17:46:50.031587
