id: ADD7DD3FF
base_file: fD861.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.036910
  last_modified_at: 2022-06-19 17:46:50.036913
