id: ADD7DD3FF
base_file: fAAF9.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.998254
  last_modified_at: 2022-06-19 17:46:49.998257
