id: ADD7DD3FF
base_file: f05CA.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.815963
  last_modified_at: 2022-06-19 17:46:49.815968
