id: ADD7DD3FF
base_file: fC200.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.020600
  last_modified_at: 2022-06-19 17:46:50.020603
