id: ADD7DD3FF
base_file: fE85F.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.052967
  last_modified_at: 2022-06-19 17:46:50.052970
