id: ADD7DD3FF
base_file: fF777.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.068175
  last_modified_at: 2022-06-19 17:46:50.068178
