id: ADD7DD3FF
base_file: fE1B5.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.043596
  last_modified_at: 2022-06-19 17:46:50.043599
