id: ADD7DD3FF
base_file: f10A8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.836821
  last_modified_at: 2022-06-19 17:46:49.836830
