id: ADD7DD3FF
base_file: fA6A8.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.988232
  last_modified_at: 2022-06-19 17:46:49.988236
