id: ADD7DD3FF
base_file: fBDB6.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.016002
  last_modified_at: 2022-06-19 17:46:50.016005
