id: ADD7DD3FF
base_file: fDA5B.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.038680
  last_modified_at: 2022-06-19 17:46:50.038683
