id: ADD7DD3FF
base_file: f252D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.909962
  last_modified_at: 2022-06-19 17:46:49.909965
