id: ADD7DD3FF
base_file: f6DCE.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.958290
  last_modified_at: 2022-06-19 17:46:49.958293
