id: ADD7DD3FF
base_file: f3E96.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.926834
  last_modified_at: 2022-06-19 17:46:49.926837
