id: ADD7DD3FF
base_file: f8E87.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.982861
  last_modified_at: 2022-06-19 17:46:49.982864
