id: ADD7DD3FF
base_file: fDB1A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.039533
  last_modified_at: 2022-06-19 17:46:50.039536
