id: ADD7DD3FF
base_file: f118C.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.846457
  last_modified_at: 2022-06-19 17:46:49.846468
