id: ADD7DD3FF
base_file: fEC20.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:50.060442
  last_modified_at: 2022-06-19 17:46:50.060445
