id: ADD7DD3FF
base_file: f6501.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:46:49.955204
  last_modified_at: 2022-06-19 17:46:49.955208
